# Generated by Django 4.2.16 on 2024-10-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendadoproduto',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
