# Generated by Django 4.2.16 on 2024-10-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vendadoproduto_qtd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendadoproduto',
            name='qtd',
            field=models.IntegerField(),
        ),
    ]
